### ISSUE TITLE
Window is hard to see

### ISSUE THREAD

**Issue by Spunkette** [emptyrivers/wow-remix-checklist#1]
Hi! Is the window here supposed to be mostly transparent? It makes it really hard to see the text in the box.

![image](https://github.com/emptyrivers/wow-remix-checklist/assets/146160999/11333ff8-4f8f-4633-94e4-a21bd2039896)

Also is that number next to the bronze icon the amount you have in total? I ask because my actual amount is 1,117,769 not 1,001,400

**Comment by emptyrivers** [comment]
Do you have the addon Paste? It's got an old strata fix library that bugs out modern scroll templates.

**Comment by emptyrivers** [comment]
[LibStrataFix.zip](https://github.com/user-attachments/files/15960678/LibStrataFix.zip)
You can replace any LibStrataFix embed in your addons with this, which should fix the problem.

**Comment by Spunkette** [comment]
> Do you have the addon Paste? It's got an old strata fix library that bugs out modern scroll templates.

Yes, I do happen to have paste. Thank you so much for the fix.
